
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.configMap.scrape_interval }}
    scrape_configs:
      - job_name: 'foxapp_exporter'
        metrics_path: {{ .Values.configMap.metrics_path }}
        static_configs:
          - targets: ['{{ .Values.configMap.exporter_target }}']

