
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: ltx
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.containerPort }}
  selector:
    app: prometheus  


