
#image:
#  image: "rootasch/demo"
#  tag: "foxexporter"  # Last one was xporter7
#  port: 8001
deployment_name: foxapp-exporter
namespace: ltx
replicaCount: 1
exporterPort: "8001"
serverUrl: "http://foxapp-service.ltx.svc"

exporter:
  image: "rootasch/json-exporter:0.1.3"
  port: 8001


